### ISSUE TITLE
Add more JS parsers

### ISSUE THREAD

**Issue by fkling** [fkling/esprima_ast_explorer#20]
- [x] babel-eslint
- [x] espree
- [x] acorn
- [x] recast
- [x] shift-ast

**Comment by hzoo** [comment]
Should we add babel-eslint still? It might not be that useful

**Comment by bgw** [comment]
It would be useful for people writing eslint rules, especially ones targeting Babel specific features. Eg, eslint-plugin-babel or some FB-internal rules. It might also be useful debugging different behaviors in the resulting ASTs.

I wouldn't say this is a high priority though, especially if there's an espree AST visualizer on the eslint website.

**Comment by fkling** [comment]
Sure we can add it, I just didn't get around to it yet :) It should be quite easy to add now though.

**Comment by hzoo** [comment]
K i'l do a PR then. There aren't any babel-eslint options so i'l remove that part.

**Comment by michaelficarra** [comment]
Please add the Shift parser. http://shift-ast.org

**Comment by hzoo** [comment]
@michaelficarra k made #28 too

**Comment by fkling** [comment]
babel-eslint and Shift are now merged!
