### ISSUE TITLE
http://astexplorer.net/ is crashing

### ISSUE THREAD

**Issue by gaearon** [fkling/esprima_ast_explorer#34]
<img width="464" alt="screen shot 2015-09-04 at 21 21 47" src="https://cloud.githubusercontent.com/assets/810438/9691428/14b2dbdc-534b-11e5-82b8-65dd95aa8a8f.png">

Chrome, OS X

**Comment by fkling** [comment]
Oh, what happens if you clear local storage?

This seems to be one of the "it works for me" cases :-/

**Comment by gaearon** [comment]
I can reliably reproduce it both in Chrome in anonymous mode with clear local storage and Safari. I never even used Safari with this website before.

**Comment by fkling** [comment]
Silly mistake on my side. If you never visited the page or changed parsers, this is the error you get. Fixed now :)

**Comment by gaearon** [comment]
Confirm as working now. :+1:
