### ISSUE TITLE
Can't recover from infinite loops

### ISSUE THREAD

**Issue by kyldvs** [fkling/esprima_ast_explorer#35]
For example, just write `while(true);` in the transform script and the whole browser will freeze when the code is run.

(practically I ran into this by introducing some accidental infinite recursion)

Instead of solving the halting problem, it would be cool if we just put a timeout on the transform and killed it after 30 seconds or so.

**Comment by fkling** [comment]
That wouldn't really help since the loop will block the event loop. The `setTimeout` callback would never run (or am I misunderstanding your suggestion?). The only solution would be to run the transform in a webworker.

**Comment by kyldvs** [comment]
Ah.. right. Is there enough support for webworkers across browsers that it would be reasonable to use them?

**Comment by kyldvs** [comment]
This is actually pretty annoying, while writing a completely safe for loop it's easy to cause an infinite loop and crash the tab. For example this puts you in an un-recoverable state if there's any valid statement after it.

```
const maxDepth = 3;
for (let i = 0; i < maxDepth;)
```

**Comment by fkling** [comment]
This should be solved now with #39.
