### ISSUE TITLE
Feature request: settings for transformer

### ISSUE THREAD

**Issue by lahmatiy** [fkling/esprima_ast_explorer#36]
Transformer doesn't work for some ES7 features like decorators. But parser works fine, as has option for it.

Simple example:

```js
@decorator
class A {}
```

This cose cause to error in transformer:

![image](https://cloud.githubusercontent.com/assets/270491/10246171/7a6fc98a-6917-11e5-8c96-32582d5b392e.png)

**Comment by hzoo** [comment]
Maybe the settings just aren't being passed correctly?

**Comment by fkling** [comment]
Babylon uses different settings than babel. For now I just enabled `stage: 0` for the Babel transformer.

**Comment by hzoo** [comment]
works for me - cool!

**Comment by lahmatiy** [comment]
Cool! Thank you!
