### ISSUE TITLE
Can't run locally for modifications

### ISSUE THREAD

**Issue by RReverser** [fkling/esprima_ast_explorer#42]
Tried to build & run locally, but got:

`TypeError: $def is not a function` in browser console in following context:

```javascript
loadjs.d("323",function(require,module,exports){
// 19.1.3.1 Object.assign(target, source)
var $def = require('./$.def');

$def($def.S + $def.F, 'Object', {assign: require('./$.assign')});
},{"./$.assign":210,"./$.def":219});

loadjs.d("949",function(require,module,exports){
```

**Comment by fkling** [comment]
Yeah, I know this issue. I'm not sure what causes it though. Using uglifyify used to solve this, I think because of dead code elimination, but maybe not anymore?

This is part of `core-js`. Maybe there is an issue with circular dependencies, not sure. @zloirock, have you seen this before?

**Comment by fkling** [comment]
Uh, look like I removed uglifyify from `npm run watch` in one of the latest commits. Will add it back, but it would still be great to find a real solution, because uglifyify slows down the build...

**Comment by zloirock** [comment]
> have you seen this before?

Sure, and each time it was mistake in build configuration. For example, `babel` not ignored `babel-runtime`.

**Comment by fkling** [comment]
After looking a bit more into the generated files, it seems that `$.def` is required from `dist/app.js`, but is only defined in `dist/parsers/babel.js`.

Not sure why it is not defined in `dist/app.js`. I expected that any direct dependency of the entry file needs is also contained in it. @arian, am I doing something wrong here?

**Comment by arian** [comment]
How do you reprodue this? I just ran esprima_ast_explorer locally, using `npm run watch`, and the `$.def` module ends up in `dist/app.js`, just like the object.assign module.

Does updating to the latest partition-bundle help? 2.2.0 fixed some problems with deduped modules.

**Comment by fkling** [comment]
Looks like I'm already using 2.2.1. I'm using

    watchify -p [partition-bundle --map partition.json --output ./ --main ./src/app] \
    -o /dev/null -v

It looks like there are two `./$.def` modules, one with ID 650 ([this one](https://github.com/zloirock/core-js/blob/02580032fcc25e37197a4bba7870bbb1506567ad/library/modules/%24.def.js)) and one with 218 ([this one](https://github.com/zloirock/core-js/blob/02580032fcc25e37197a4bba7870bbb1506567ad/modules/%24.def.js)), i.e. they are definitely different modules. 650 is indeed contained in `dist/app.js`, but 218 is not (not sure if you'd get the same numbers in your build).

The are quite a few modules in `dist/app.js` referencing 218, e.g.

```js
﻿loadjs.d("322",function(require,module,exports){
// 19.1.3.1 Object.assign(target, source)
var $def = require('./$.def');

$def($def.S + $def.F, 'Object', {assign: require('./$.assign')});
},{"./$.assign":209,"./$.def":218});
```

but `loadjs.d("218", ...)` is  in `dist/parsers/babel.js`.

I guess reusing the same (relative) module name shouldn't matter?

**Comment by fkling** [comment]
I'll check if using webpack would solve this.

**Comment by RReverser** [comment]
@fkling Yes please! Currently scripts section using combination of browserify with some NIX-specific things so that I couldn't even contribute from own Windows machine :(

**Comment by fkling** [comment]
I switched to webpack in 89db32fcfb1bdab3dfd07b7317c7e40faa4c66c2. It seems to work well so far. Let me know how it works for you.

**Comment by RReverser** [comment]
Still seeing a bunch of webpack warnings on build (like, trying to `require` `.md` files somewhere and so on), but other than that, seems to build fine. Thanks!

**Comment by fkling** [comment]
Yeah, I didn't figure out where it would try to load an `.md` file, but everything worked for me so I didn't bother with it too much.
