### ISSUE TITLE
Add Babel 6

### ISSUE THREAD

**Issue by fkling** [fkling/esprima_ast_explorer#47]
Because Babel 6 uses a slightly different AST and plugin definition, I think it makes sense to add it as separate option (parser and transformer) instead of just upgrading Babel.

**Comment by hzoo** [comment]
Yep I think so as well

**Comment by hzoo** [comment]
How can we specify multiple versions of a dependency in npm? so we just change the alias and link to something? I guess its different since babylon is under the babel/babel repo?

**Comment by fkling** [comment]
Oh good point, I haven't thought about that :-/

**Comment by fkling** [comment]
I guess I could add Babel as a submodule and link that? Or maybe I have to create a "wrapper package".

**Comment by fkling** [comment]
I found a way to do this, but currently have problems getting the new plugin example to work...

**Comment by hzoo** [comment]
Awesome! - um I can take a look later

**Comment by fkling** [comment]
I can push my changes later to a new branch.

**Comment by fkling** [comment]
See https://github.com/fkling/esprima_ast_explorer/tree/babel6

**Comment by fkling** [comment]
Added with 58bde51b38138b6d6ededef46be02a029446c5e3. There might be a better way than creating these pseudo modules, but it works ;)
