### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by kentor** [fkling/esprima_ast_explorer#53]
none of the buttons in the nav seems to be working...

**Comment by fkling** [comment]
They work fine for me. Do you get any errors in the console? Which browser are you using?

**Comment by kentor** [comment]
ah http://felix-kling.de/esprima_ast_explorer/ wasn't working. was getting 404s on 
```GET http://felix-kling.de/dist/7.bundle.js``` and ```GET http://felix-kling.de/dist/0.bundle.js ```

But, http://astexplorer.net/ does work

**Comment by fkling** [comment]
Oh I see. Maybe I can build the URLs so that they'd work on both domains.

**Comment by phuu** [comment]
@fkling This was my issue. Thanks.

**Comment by fkling** [comment]
I fixed that with 7589ba611c03039a287079b79f2d46413366fa3e, but please use http://astexplorer.net instead.
